language: java
sudo: required
script: mvn package

addons: 
   coverity_scan: 
     project: 
       name: "ontheFlyoct15/UsageDashboard" 
       description: "Build submitted via Travis CI" 
     notification_email: coolyogs@ymail.com
     build_command_prepend: "mvn clean" 
     build_command:   "mvn -DskipTests=true compile" 
     branch_pattern: coverity_scan 
